language: node_js

node_js:
- "8"

cache:
  directories:
  - /home/travis/.elm/0.19.0/package

os:
- linux

before_install:
- node --version
- npm --version
- npm install -g elm

install:
- npm install

script:
  - npm test
