environment:
  matrix:
  - nodejs_version: "8"

cache:
- '%APPDATA%\elm\0.19.0\package'

platform:
- x64

matrix:
  fast_finish: true

init:
# report build worker details
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
# update node version
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
- node --version
- npm --version

# install dependencies
- npm install -g elm
- npm install

build: off

test_script:
  - npm run test-ci

on_finish:
  - ps: |
        $wc = New-Object "System.Net.WebClient"
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "unit-tests.xml"))

