environment:
  ELM_VERSION: "0.18.0"
  matrix:
  - nodejs_version: "5.0"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install

build: off

test_script:
  - npm test-ci

on_finish:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-Item 'unit-tests.xml'  |
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        
